run:
  tests: false
  skip-dirs:
      - src/service/mocks

linters:
  disable-all: false
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - gomnd
    - lll
    - nakedret
    - testpackage
    - wsl